version: '3'
services: 
  web: 
    build:    # the dot implies that there is a 'Dockerfile' in the $pwd. But the name is 'Dockerfile.dev'. so..
      context: .  # this specifies where all files is pulled from for the image.
      dockerfile: Dockerfile.dev #name of the custom docker file
    ports:
    - "8000:3000"
    volumes:
    - /app/node_modules
    - .:/app          # map current pwd to /app inside the container

  # Setting up another service for tests
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] #Overring the "npn run start" command in Dockerfile.dev
